lab_6/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index , name ='index'),
    path('tambahStatus/', views.tambahStatus, name='tambahStatus')
]

ppw6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab_6.urls')),
]

lab_6/models.py
from django.db import models

# Create your models here.
class Kabar(models.Model):
    status = models.CharField(max_length = 300)
    waktu = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.status

lab_6/forms.py
from django import forms

class Status(forms.Form):
    status = forms.CharField(label='Status',required= True, max_length=300,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Enter your Status'}))

lab_6/views.py
from django.shortcuts import render, redirect
from .forms import Status
from .models import Kabar
from django.views.decorators.http import require_POST

# Create your views here
def index(request):
    list_status = Kabar.objects.order_by('-waktu')
    form = Status()
    context = {'list_status': list_status, 'form': form}
    return render(request, 'landing.html', context)

@require_POST
def tambahStatus(request):
    form = Status(request.POST)

    if form.is_valid():
        new_status = Kabar(status = request.POST['status'])
        new_status.save()
    
    return redirect ('homepage:index')

lab_6/templates/landing.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Oswald|Quicksand&display=swap" rel="stylesheet">
    <title>TDD</title>
</head>
<style>
    .status button{
        border-radius: 5px;
        background-color: white;
        color: black ;
        border: 1.5px solid black;
    }
    .status button:hover{
        background-color: gainsboro;
        border-radius: 5px;
    }
    .statusOut div{
        display: flex;
        flex-direction: column;
        justify-content: center;
        text-align: center;
    }
    .bungkus-status{
        display: flex;
        flex-direction: row;
        justify-content: center;
        text-align: center;
    }
</style>
<body>
    <div class="status">
        <h1 style="text-align: center; margin-top: 100px; font-family: 'Oswald', sans-serif;">Hello, Apa Kabar?</h1>
        <form action="{% url 'homepage:tambahStatus'%}" method="POST" role="form" style="text-align: center; margin-top: 20px;">
            {% csrf_token %}
            <label for="status" id ="status">
                {{form.status}}
            </label>
            <button type="submit" style="font-family: 'Quicksand', sans-serif;" class="ml-2" id="submit">Submit</button>
        </form>
    </div>

    <div class="bungkus-status">
        <div class="statusOut mt-3">
            <div>
                {%for i in list_status%}
                <hr>{{i.status}}
                {%endfor%}
            </div>
        </div>
        <div class="statusOut mt-3 ml-5">
            <div>
                {%for i in list_status%}
                <hr>{{i.waktu}}
                {%endfor%}
            </div>
        </div>
    </div>
</body>
</html>